---
title: "There is no R in Entomology (but there is one in Reproducible)"
author: "Drew Tyre"
date: "November 11, 2015"
output:  
  ioslides_presentation:
    css: css/custom.css

---

## Outline for the webinar
1. Why worry? (and why R?)
2. a whiRlwind touR
3. Organizing your workflow
4. Version Control & Collaboration
5. Wrapping up

## Publicly available

- All code, presentations, examples etc. licensed CC BY-NC-SA 4.0
- Available here: [github.com/atyre2/noRinEntomology](https://github.com/atyre2/noRinEntomology)

## Why Worry? 
> - Personal Reasons -- Drew and the revisions
> - Credibility
    * The 1^st^ leg of the science-policy interface (Cash et al 2003)
    * Stephen Heard's blogpost [Reproducibility, your methods, and 400 years of Angst](http://bit.ly/1wVSkmk) 
> - Average scientist spends 30% of time developing software
    * 90% are self taught! (Wilson et al. 2014)
  
## Why R?
- Free
- Widely used 
- Rapid development (not always good ...)
- Total integration of analysis and graphics

## S came before R
- “S” invented by Rick Becker, John Chambers, Allan Wilks at AT&T Labs
- Emphasis on graphics and modelling
- S-PLUS is the commercial implementation
- **R**oss Ihaka and **R**obert Gentleman, U of Auckland wrote a version of the S language, released under a GPL in 1995

## Why RStudio?
- Free ... 
- Reduces errors (Brace matching, syntax highlighting)
- Integrates "knitting" analysis and text together
- Integrates version control

# staRting the touR

## Take a look at R/RStudio
- R as a calculator

## Can be done elsewhere
- SAS now has a documentation system
- LaTex works with anything
- Less integration; more manual work

# Organizing your workflow

## Put everything in one directory
- All the code, data, outputs etc. 
- Make this directory an *RStudio Project*
- This will always be the "working directory"


## Use relative paths
- Breaks on another computer, OS, user
```
mydataframe <- read.csv(
"C:\\users\\Drew\\Box Sync\\Teaching\\noRinEntomology\\data\\e418.csv")
```
- Works with all OS, for any computer if directory is copied completely. Easier to read. 
```
mydataframe <- read.csv("data/e418.csv")
```

## NoSpaces
- spaces in filenames and directories cause problems for automation
- use camelBack style filenames for readibility
  - UpperCamelCase
  - lowerCamelCase 

## One useful structure
```
noRinEntomology
|   .Rhistory
|   LICENSE.md
|   noRinEntomology.html
|   noRinEntomology.rmd
|   noRinEntomology.Rproj
|   README.md
|   
+---code
|       custom.css
|       downLoadData.r
+---data
|       e418.csv
|
\---images
        good_directory_screenshot.png
        Ugly_directory_screenshot.png
        UNL-2C-TAG-small.png
```

## Why put code in a sub-directory?
- Reduces clutter
- Enables re-use between output documents
- Warning -- relative paths start from project working directory 

## Example: plot of species richness
```{r speciesRichness, message=FALSE}
source("code/calculateRichness.r")
library(lattice)
xyplot(InsectRich~jitter(Year)|NumSp,data=spRichData)
```

# Everything is a text file

## Write scripts!

- A script is a text file with commands for the computer
- Human readable
- Provides documentation for everything done to the data

## Keep raw data in text files

- If possible -- large data causes problems
- Most future proof format
- easy to check
- Treat data as "read-only"
- Do "data cleaning" in scripts -- REPRODUCIBLE! DOCUMENTED!

## Don't trust the workspace

- best practice: rerun all code everytime you start working
- gets complicated with long-running analyses
 

# Version Control and collaboration

## Version control

<<<<<<< HEAD
- What was done when and by who
- Back up to previous versions
- Anything manually created should be in version control
- Ghetto VC: put the date in the file name and comments at the start
    - Filename explosion! 
=======
> - What was done when and by who
> - Back up to previous versions
> - Anything manually created should be in version control
> - Ghetto VC: put the date in the file name and comments at the start
      - Filename explosion! 
>>>>>>> eb7f3ed97015aa7e36128184fd428d6523923a42

## Collaboration -- sharing with others
- sending code and data via email is fragile
- Use dropbox: download R file at this link:
http://bit.ly/1OhG7zR
- Code has direct link to data
```
blowflies <- source_DropboxData("blowflytest.csv","o0jguchss5vu2ct",                             sha1="12e7d4c54860cf9631c06923eab5f81d64d179c9",
                                cache=TRUE)
```
## More on Dropbox ... 

<div class="columns-2">

  <div class="centered">*Good:*</div>
  - upload new version with same name old version still available for 30 days (longer with paid account)
  - Can share an entire folder with collaborators -- all can upload/download


 <div class="centered">*Bad:*</div>
  - Old keys still point to old versions, even though updated version available
  - No documentation of what changed in new version
</div>

## Optimal -- use Git
- Version control system built into RStudio
- Install, turn on for each project
    * Demonstrate
- Can hook up to a "remote repository" for sharing
    * Github - free but public
    * Your institution can run GitLab locally
  
# Wrapping up

## What next?

> - Download R & RStudio and get started!
> - Software / Data Carpentry workshops
> - Read Gandrud (2015)
> - Take my courses! "From zeRo to heRo in 16 weeks" (contact me atyre2@unl.edu)


## References

Cash et al (2003) Knowledge systems for sustainable development PNAS 100, 8086-8091.

Gandrud, C. (2015) Reproducible Research with R and RStudio. CRC Press, London.

Wilson G, Aruliah DA, Brown CT, Chue Hong NP, Davis M, et
al. (2014) Best Practices for Scientific Computing. PLoS Biol 12(1): e1001745. doi:10.1371/journal.pbio.1001745
  